services:
  proxy:
    pull_policy: always
    image: kokimorino/mweb-proxy:latest
    depends_on:
      - api
    ports:
      - 8080:8080
  api:
    pull_policy: always
    image: kokimorino/mweb-api:latest
    expose:
      - 8000
    volumes:
      - /data
