services:
  proxy:
    restart: always
    image: kokimorino/mweb-proxy:latest
    depends_on:
      - api
    ports:
      - 80:8080
    volumes:
      - "/shared/log/nginx:/var/log/nginx"
  api:
    restart: always
    image: kokimorino/mweb-api:latest
    expose:
      - 8000
    volumes:
      - "/shared/log/api:/log"
      - "/shared/db:/data"
