# Don't merge compose files as it's hard to read.
# Make multiple files for multiple environments.

services:
  proxy:
    restart: always
    image: kokimorino/mweb-proxy:latest
    depends_on:
      - api
    ports:
      - 80:8080
  api:
    restart: always
    image: kokimorino/mweb-api:latest
    expose:
      - 8000
    volumes:
      - "/shared/db:/data"
