#cloud-config

groups:
  - terraform

users:
  - default
  - name: koki
    gecos: Koki Morino
    shell: /bin/bash
    primary_group: terraform
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDG7jJJaWeZR+rvuYOJncQeMDsFerOZrgsEJOunHJYxSnqLsJA71awyR1BMt/1nExpJbc3vZfil/9sozBLGClMALiQiVmZf6lRHSxiL106moKQIgksiGYwv+lI/Q9h4WZi2rxXp1ZbcuUgeIDivC/hXHqpIrIfGaE7jj2rccet3h/W6pUVUs1riPsAKKU3U4VJPJZ0lR6kezEzjnp6d8396wQ7qIVQiSoxkh9XxcRqXV8hbJd5/6oAj3I6eTTA17jgnXbLjCacdk+nchak7aApM2SoTN7NEfbVqWfA2weX6o1K11XaQY2/GVug3V5g0ybJ+KLmU4qJrRJanJNkT4a2lHIUorvdCSW8M2CRrHtWJWY0kl+ScoHjddsqNWqDePGmlAcW8JM08GZ30TqLoBCMOQgSO7fVa/BmZ24/rD3lwRVUk5lfOOvWKxPEwEQKOjpEexGfkgB0uqypVr3OwreRSO3GKAA5GGLSDoxSlVwh71H+SIJeTmtsKLel2OzBw1rc= koki

runcmd:
  - sudo su koki
  - sudo apt-get update
  - sudo apt-get upgrade -y
