name: memkept
description: "Memory keeping"
# Do NOT publish.
publish_to: "none"
# Fix optional number on +1.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  logging: ^1.2.0
  protobuf: ^3.1.0
  uuid: ^4.5.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Noto_Sans_JP/
