[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
